services:
  app:
    image: todo-front-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:80
    container_name: todo-front-prod
    environment:
      - VITE_BACKEND_URL
