services:
  app:
    image: todo-front-dev
    # build:
    #   context: .
    #   dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 5173:5173
    container_name: todo-front-dev2
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api

  mongo:
    image: initialized-mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  server:
    image: todo-back-dev
    volumes:
      - ./todo-backend:/usr/src/app
    ports:
      - 3000:3000
    container_name: todo-back-dev2
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
